### ISSUE TITLE
Error in rendering

### ISSUE THREAD

**Issue by werwack** [ubisoft/stampinfo#2]

**Comment by werwack** [comment]
OS: Mac
StampInfo Version: 1.0.12
<img width="906" alt="renderError_stampinfo_mac" src="https://user-images.githubusercontent.com/15678244/134657518-1990460c-ff48-4062-a186-dd0f12748bfe.png">

**Comment by werwack** [comment]
_It's me again sorry! I'm having an issue with where Blender config files are stored when I launch Blender in admin mode. It (Blender) seems to create a new environment at this location /var/root/Library/Application Support/Blender/3.0/, which I cannot access. The usual location for config files on Mac is this one /Users/piotrnikov/Library/Application Support/Blender/3.0.
It's a problem if I want to copy my old setup (from my account) to this new one (admin)._

Hello Piotr,
I'm not on Mac but I will attempt to help.
Question: why do you need to move all your config to the admin context?
The lanch of Blender in Admin mode is only required for the time you install the add-on. Once the add-on is installed close the app and use it normally.

**Comment by piotrnikov** [comment]
@werwack 
Thanks again for your patience!! 
I'm not used to the admin thing so it confused me.
Just in case someone out there has the same problems as me:
. Install this addon in Blender admin mode (type "sudo /Applications/Blender.app/Contents/MacOS/Blender" in a terminal window).
. Close Blender.
. Launch a regular Blender (non admin), **and install the addon again**. All the dependencies should work (because already installed thanks to the admin step).
I wasn't installing the addon **again** in my regular Blender, that's why it wasn't working.
This all might be a bit confusing for regular Blender users.
But maybe not :)
